import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id);
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash(seed);return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const pick=(r,a)=>a[Math.floor(r()*a.length)], range=(r,a,b)=>a+(b-a)*r(), ri=(r,a,b)=>Math.floor(range(r,a,b+1));
const STONES={Diamond:0xffffff,Ruby:0xa60d24,Sapphire:0x183d8f,Emerald:0x087a55,Spinel:0xd12855,Tourmaline:0x176f66,Aquamarine:0x8ccad8,Topaz:0x7db4db,Amethyst:0x75458f,Citrine:0xd89d28,Garnet:0x6d1822,Peridot:0x8cad42,Tanzanite:0x554a9f,Opal:0xe9e0cf,'Rock Crystal':0xe9f1f0,Jadeite:0x5c9b76,Onyx:0x111111,Obsidian:0x241f24,Labradorite:0x607778,Turquoise:0x36aeb2,'Lapis Lazuli':0x244a8d,Coral:0xc94f48,Pearl:0xf2e9dc};
const CUTS=['Round Brilliant','Oval','Emerald Cut','Asscher','Princess','Cushion','Pear','Marquise','Trillion','Rose Cut','Cabochon','Slab'];
const MODES=['center','cluster','pave','pearl','slab','cabochon'];
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(35,1,.1,1000), renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;camera.position.set(0,4.5,11);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x44382f,2.4));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(5,7,8);scene.add(key);const rim=new THREE.DirectionalLight(0xffe0c0,2);rim.position.set(-6,1,-5);scene.add(rim);
let object=new THREE.Group();scene.add(object);let current={};
function resize(){const p=renderer.domElement.parentElement,w=p.clientWidth,h=p.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);
function metalMaterial(name){let c=0xd6d6d6;if(name.includes('Yellow'))c=0xd5a43b;if(name.includes('Rose'))c=0xc48773;if(name.includes('Platinum'))c=0xcfd1d2;if(name.includes('Silver'))c=0xc9c9c9;return new THREE.MeshPhysicalMaterial({color:c,metalness:1,roughness:.18,clearcoat:.35,clearcoatRoughness:.12})}
function gemMaterial(name){return new THREE.MeshPhysicalMaterial({color:STONES[name]||0xffffff,metalness:0,roughness:name==='Pearl'?.28:.08,transmission:['Onyx','Obsidian','Lapis Lazuli','Turquoise','Coral','Pearl','Jadeite'].includes(name)?0:.48,thickness:1.5,ior:1.75,transparent:true,opacity:.94,clearcoat:1})}
function gemGeo(cut,size){if(cut==='Pearl')return new THREE.SphereGeometry(size,40,24);if(cut==='Cabochon')return new THREE.SphereGeometry(size,40,20,0,Math.PI*2,0,Math.PI*.55).scale(1, .82,.62);if(cut==='Slab')return new THREE.CylinderGeometry(size*.78,size*.9,size*.34,ri(()=>.5,6,8));let seg=cut==='Princess'||cut==='Asscher'||cut==='Emerald Cut'?4:cut==='Trillion'?3:cut==='Marquise'?12:cut==='Pear'?18:cut==='Cushion'?8:32;let g=new THREE.CylinderGeometry(size*.72,size,size*.58,seg,1,false);if(cut==='Oval')g.scale(1.35,1,.9);if(cut==='Marquise')g.scale(1.65,1,.72);if(cut==='Emerald Cut')g.scale(1.35,1,.8);if(cut==='Pear')g.scale(1.2,1,.82);return g}
function addGem(group,name,cut,size,pos,rot=[Math.PI/2,0,0]){const m=new THREE.Mesh(gemGeo(cut,size),gemMaterial(name));m.position.set(...pos);m.rotation.set(...rot);group.add(m);return m}
function torusMetal(group,mat,R,tube,scale=[1,1,1],rot=[0,0,0]){const m=new THREE.Mesh(new THREE.TorusGeometry(R,tube,28,128),mat);m.scale.set(...scale);m.rotation.set(...rot);group.add(m);return m}
function generate(){while(object.children.length)object.remove(object.children[0]);const seed=$('seed').value||'AGDP';const r=rng(seed);const type=$('type').value, metal=$('metal').value;let mode=$('stoneMode').value==='auto'?pick(r,MODES):$('stoneMode').value;let stone=$('stone').value==='auto'?pick(r,Object.keys(STONES)):$('stone').value;let cut=$('cut').value==='auto'?pick(r,CUTS):$('cut').value;if(mode==='pearl'){stone='Pearl';cut='Pearl'}if(mode==='pave')cut='Pavé';if(mode==='slab')cut='Slab';if(mode==='cabochon')cut='Cabochon';const mat=metalMaterial(metal), architectural=range(r,.25,.92), asym=range(r,.05,.7), primary=range(r,.65,1.35), stoneCount=mode==='pave'?ri(r,18,54):mode==='cluster'?ri(r,3,9):mode==='pearl'?ri(r,1,7):1;
if(type==='ring'){const R=2.25,t=.28+architectural*.22;torusMetal(object,mat,R,t,[1,1,1]);const crown=new THREE.Mesh(new THREE.BoxGeometry(1.3+architectural, .55, .55+asym),mat);crown.position.y=R-.02;crown.rotation.z=(asym-.35)*.25;object.add(crown);placeStones(r,mode,stone,cut,stoneCount,primary,[0,R+.45,0],1.35)}
else if(type==='pendant'){torusMetal(object,mat,2.1,.24+architectural*.18,[.82+asym*.25,1.05,1]);const bar=new THREE.Mesh(new THREE.BoxGeometry(.28,1.05,.35),mat);bar.position.y=2.55;object.add(bar);placeStones(r,mode,stone,cut,stoneCount,primary,[0,.15,.32],1.55)}
else if(type==='brooch'){const frame=new THREE.Mesh(new THREE.TorusGeometry(2.15,.34,24,8),mat);frame.scale.set(1.25,.78,1);frame.rotation.z=asym*.35;object.add(frame);placeStones(r,mode,stone,cut,stoneCount,primary,[.2,.1,.35],1.8)}
else if(type==='earring'){for(const sx of [-1,1]){const g=new THREE.Group();g.position.x=sx*2.35;torusMetal(g,mat,1.45,.20+architectural*.1,[.78,1,1]);placeStones(r,mode,stone,cut,Math.max(1,Math.ceil(stoneCount/2)),primary,[0,-.2,.24],1.0);object.add(g)}}
else if(type==='cuff'){const m=torusMetal(object,mat,2.65,.34+architectural*.16,[1.12,.82,1],[Math.PI/2,0,0]);m.geometry.deleteAttribute?.('uv');placeStones(r,mode,stone,cut,stoneCount,primary,[0,2.05,.2],1.7)}
else {for(const sx of [-1,1]){const g=new THREE.Group();g.position.x=sx*2;const face=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.05,.45,8),mat);face.rotation.x=Math.PI/2;g.add(face);placeStones(r,mode,stone,cut,Math.max(1,Math.ceil(stoneCount/2)),primary,[0,0,.32],.82);object.add(g)}}
object.rotation.x=-.12;object.rotation.z=(asym-.35)*.12;current={seed,type,metal,mode,stone,cut,stoneCount,architectural:architectural.toFixed(2),asymmetry:asym.toFixed(2),primaryStoneMm:(primary*7).toFixed(1),status:'DESIGN STUDY — bench review required'};renderSpec();$('occurrence').textContent='OCCURRENCE '+seed.toUpperCase()}
function placeStones(r,mode,stone,cut,n,size,center,spread){if(mode==='pave'){for(let i=0;i<n;i++){const a=(i/n)*Math.PI*2+range(r,-.06,.06),rad=spread*range(r,.58,1);addGem(object,stone,'Round Brilliant',.09+size*.07,[center[0]+Math.cos(a)*rad,center[1]+Math.sin(a)*rad,center[2]+range(r,-.08,.12)])}}else if(mode==='cluster'||mode==='pearl'){for(let i=0;i<n;i++){const a=range(r,0,Math.PI*2),rad=spread*Math.sqrt(r())*.55;addGem(object,stone,mode==='pearl'?'Pearl':cut,.18+size*range(r,.22,.42),[center[0]+Math.cos(a)*rad,center[1]+Math.sin(a)*rad,center[2]+range(r,-.05,.2)])}}else addGem(object,stone,cut,.34+size*.35,center)}
function renderSpec(){const labels={seed:'SEED',type:'TYPOLOGY',metal:'METAL',mode:'STONE MODE',stone:'STONE',cut:'CUT / FORMAT',stoneCount:'STONE COUNT',primaryStoneMm:'PRIMARY SCALE',architectural:'STRUCTURAL LOAD',asymmetry:'ASYMMETRY',status:'PRODUCTION STATUS'};$('spec').innerHTML=Object.entries(current).map(([k,v])=>`<div class="spec-row"><b>${labels[k]||k.toUpperCase()}</b><span>${v}${k==='primaryStoneMm'?' mm':''}</span></div>`).join('')}
$('generate').onclick=generate;$('randomSeed').onclick=()=>{$('seed').value='AGDP-'+Math.random().toString(36).slice(2,8).toUpperCase();generate()};$('download').onclick=()=>{const blob=new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${current.seed}-study.json`;a.click();URL.revokeObjectURL(a.href)};['type','metal','stoneMode','stone','cut'].forEach(id=>$(id).onchange=generate);
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}resize();generate();animate();
